name: Feature Request
description: Request a new feature or change to an existing feature
title: "[Feature Request]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
    validations:
      required: false
  - type: textarea
    id: feature-request
    attributes:
      label: Describe your request
      description: Also, please describe why you'd like to see this change.
      placeholder: I would like to request...
    validations:
      required: true
  - type: textarea
    id: possible-implementation
    attributes:
      label: Possible Implementation
      description: If you can, describe how this might be implemented.
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/upgradejs/plugin-preloader/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
